
### 📊 Market Overview
*Last Updated: 2026-10-05 03:14:51 (UTC)*

| Total Market Cap | 24h Change | 7d Change |
| :--- | :--- | :--- |
| **$292,485,780,497** | 🟢 +0.06% | 🔴 -0.07% |

### 📰 Latest News
- [Visa, Mastercard, Stripe, and Coinbase Commit $1 Billion to New Stablecoin: Is Open USD a Challenge to Tether, USDC, and RLUSD? - Yahoo Finance](https://news.google.com/rss/articles/CBMipgFBVV95cUxQaE4zNmxuT1g5ancxRVNJSWhlSHRlMXg4UGhzMmVuMXFjS2lzZ1RfNTNYclNqdF9hVU9XdjVZZ1F5bEtjZy1CTjA4RjN6TG9OVHZ1dG9CWERZM3hsYUpXNW1RRXlwbmRrMXJ3MWkzcnJqNW14R0JpcjBXZkgtR3BNczd4VWFWWFgzSWIxUVJmM1FhRU1pYldyWDk3RzRHLTFtZTV3Rm93?oc=5) (Sun, 04 Oct 2026 15:00:08 GMT)
- [Visa, Mastercard, Stripe, and Coinbase Commit $1 Billion to New Stablecoin: Is Open USD a Challenge to Tether, USDC, and RLUSD? - 24/7 Wall St.](https://news.google.com/rss/articles/CBMiigJBVV95cUxPVUFITnotYmk0M0hoOHNQWHZJMktIdXhRd05IV2ZuY0FCZldFbExyMW1UWUdYMEdLN3U1em9HMEZUVFNXZU9icjhhMnlpNjFydnBaZktwZHpzeGgyN19ZYXpOWlVGdVZ4ZUtxbWJpb2Z4M3ZxR3cyTWtlU1ZmUkZzZFV0Y2lvSFdfd3FqUEJ2eThmRzdGMURReWJuNjhUWS03REFHRC1wX2lBWTBIZDhRYkI1MFdQemMyTzNqSm5sRUxnN2NuaUpVem0xWF9nQXYwelA3ZUpSUE4zT3RuOTcxSWtpMmMxUF9ENUVYTUotOUlHOEl1SGFsSHFfcWhBaWF4MDNrUHFKRF9Vdw?oc=5) (Sun, 04 Oct 2026 15:00:00 GMT)
- [Tether Brings Its $184 Billion Stablecoin Back to Bitcoin: Will BTC Regain Its Role as a Payments Network? - 24/7 Wall St.](https://news.google.com/rss/articles/CBMi9AFBVV95cUxNYzZ0TWxMWTB6TUh6Z3hMVl9COTAwSldXbmlmZU5mUVg5aFYwZEx5VmE0eV9KcWt1YWNJN1lmc0w4NlkyVWRNUGtJLUxWbmF0dkhROC1jTGJ2eHVyY08yY1VoU29EZ25YRHpfeHk1RW9XVU4zYlo1aE16QXA3c1YtSTR0NDFrTWw5V1dDeERJUXhia3NQSE5OMFJKbDRnUDN5akYyTXhLRDJhUnlyTm1oVWdoN2Nfb3hwMjJLXzVTSXlXWHE0RXBSS3pxMERnZVk5dUJWRnVDclBrR3ZFalRFVWV2OEpRd3VTRG1VZkRXa0o2ZVM3?oc=5) (Sun, 04 Oct 2026 13:00:00 GMT)
- [Can Coinbase (COIN) Turn Citi’s Stablecoin Partnership Into a Durable Institutional Advantage? - Yahoo Finance](https://news.google.com/rss/articles/CBMioAFBVV95cUxQeHJSUGw2Z0lYdEE0azh4blFwZFJpYmpZN2xVNnNyWUVHZTNfMXZ6UktOOXRHeklaX0xrdVpBOE9FVzNnYmkxSXYwVktxMEw2U0hWQlludS1xSUZFRndSMTdzVVBRdGhvay1XUXJkVzI1SnQzOGVnUFUwUDdtOE14RGdZYXpIVGpDRTJUVTlhaDJLcmlrT3E2UnJjdVZwX1hF?oc=5) (Sun, 04 Oct 2026 02:09:00 GMT)
- [SoFi’s US$25 Billion Card Portfolio Shift To Bank-Issued Stablecoin Might Change The Case For Investing In SoFi Technologies (SOFI) - Yahoo Finance](https://news.google.com/rss/articles/CBMikgFBVV95cUxNdWN2Q2tYbXVvejlQWndFcl91SXZfV0pBNnBKTTl6ZFRCU1NMaDFEWHc4cXllZjR1STR3eFJEbFRIdGZrTUs1dVA3TkxhRmI5RXRwbHlFVVFJU1JiNFV1UW8xSi1sVm5JeXVxTXN5blhhWF9TRS1Nam80bEN6TmdVN2VPQ2tBYXBaOGpTY3VKSUZjUQ?oc=5) (Sun, 04 Oct 2026 02:08:00 GMT)
